# Generated by Django 4.2.3 on 2025-09-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('template', models.FilePathField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
